# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anacondaCasino.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(781, 454)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_Goal = QtGui.QFrame(self.centralwidget)
        self.frame_Goal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Goal.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Goal.setObjectName(_fromUtf8("frame_Goal"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_Goal)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frameGoalMedal = QtGui.QFrame(self.frame_Goal)
        self.frameGoalMedal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameGoalMedal.setFrameShadow(QtGui.QFrame.Raised)
        self.frameGoalMedal.setObjectName(_fromUtf8("frameGoalMedal"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frameGoalMedal)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_GoalMedal = QtGui.QLineEdit(self.frameGoalMedal)
        self.lineEdit_GoalMedal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_GoalMedal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_GoalMedal.setObjectName(_fromUtf8("lineEdit_GoalMedal"))
        self.gridLayout_4.addWidget(self.lineEdit_GoalMedal, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.frameGoalMedal)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 2, 1, 1, 1)
        self.checkBox_GoalMedal = QtGui.QCheckBox(self.frameGoalMedal)
        self.checkBox_GoalMedal.setObjectName(_fromUtf8("checkBox_GoalMedal"))
        self.gridLayout_4.addWidget(self.checkBox_GoalMedal, 1, 0, 1, 1)
        self.checkBox_Reload = QtGui.QCheckBox(self.frameGoalMedal)
        self.checkBox_Reload.setEnabled(True)
        self.checkBox_Reload.setCheckable(True)
        self.checkBox_Reload.setChecked(True)
        self.checkBox_Reload.setObjectName(_fromUtf8("checkBox_Reload"))
        self.gridLayout_4.addWidget(self.checkBox_Reload, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frameGoalMedal)
        self.frameSchedule = QtGui.QFrame(self.frame_Goal)
        self.frameSchedule.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSchedule.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSchedule.setObjectName(_fromUtf8("frameSchedule"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameSchedule)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_Schedule1 = QtGui.QFrame(self.frameSchedule)
        self.frame_Schedule1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Schedule1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Schedule1.setObjectName(_fromUtf8("frame_Schedule1"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_Schedule1)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_13 = QtGui.QLabel(self.frame_Schedule1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_9.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_Schedule1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_9.addWidget(self.label_14, 0, 1, 1, 1)
        self.timeEdit_Start1 = QtGui.QTimeEdit(self.frame_Schedule1)
        self.timeEdit_Start1.setTime(QtCore.QTime(12, 0, 0))
        self.timeEdit_Start1.setObjectName(_fromUtf8("timeEdit_Start1"))
        self.gridLayout_9.addWidget(self.timeEdit_Start1, 1, 0, 1, 1)
        self.timeEdit_End1 = QtGui.QTimeEdit(self.frame_Schedule1)
        self.timeEdit_End1.setTime(QtCore.QTime(13, 0, 0))
        self.timeEdit_End1.setObjectName(_fromUtf8("timeEdit_End1"))
        self.gridLayout_9.addWidget(self.timeEdit_End1, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_Schedule1, 2, 0, 1, 1)
        self.frame_Schedule2 = QtGui.QFrame(self.frameSchedule)
        self.frame_Schedule2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Schedule2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Schedule2.setObjectName(_fromUtf8("frame_Schedule2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_Schedule2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.timeEdit_Start2 = QtGui.QTimeEdit(self.frame_Schedule2)
        self.timeEdit_Start2.setTime(QtCore.QTime(3, 0, 0))
        self.timeEdit_Start2.setObjectName(_fromUtf8("timeEdit_Start2"))
        self.gridLayout_10.addWidget(self.timeEdit_Start2, 2, 0, 1, 1)
        self.timeEdit_End2 = QtGui.QTimeEdit(self.frame_Schedule2)
        self.timeEdit_End2.setTime(QtCore.QTime(4, 0, 0))
        self.timeEdit_End2.setObjectName(_fromUtf8("timeEdit_End2"))
        self.gridLayout_10.addWidget(self.timeEdit_End2, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame_Schedule2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_Schedule2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_Schedule2, 6, 0, 1, 1)
        self.checkBox_Schedule2 = QtGui.QCheckBox(self.frameSchedule)
        self.checkBox_Schedule2.setObjectName(_fromUtf8("checkBox_Schedule2"))
        self.gridLayout_5.addWidget(self.checkBox_Schedule2, 5, 0, 1, 1)
        self.checkBox_Schedule1 = QtGui.QCheckBox(self.frameSchedule)
        self.checkBox_Schedule1.setObjectName(_fromUtf8("checkBox_Schedule1"))
        self.gridLayout_5.addWidget(self.checkBox_Schedule1, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frameSchedule)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.frame_Goal)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.verticalLayout_2.addWidget(self.commandLinkButton)
        self.pushButtonRun = QtGui.QPushButton(self.frame_Goal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRun.sizePolicy().hasHeightForWidth())
        self.pushButtonRun.setSizePolicy(sizePolicy)
        self.pushButtonRun.setMinimumSize(QtCore.QSize(75, 46))
        self.pushButtonRun.setAutoRepeatDelay(300)
        self.pushButtonRun.setAutoDefault(False)
        self.pushButtonRun.setDefault(False)
        self.pushButtonRun.setFlat(False)
        self.pushButtonRun.setObjectName(_fromUtf8("pushButtonRun"))
        self.verticalLayout_2.addWidget(self.pushButtonRun)
        self.gridLayout_2.addWidget(self.frame_Goal, 0, 3, 1, 1)
        self.frameLog = QtGui.QFrame(self.centralwidget)
        self.frameLog.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameLog.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLog.setObjectName(_fromUtf8("frameLog"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameLog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textEdit = QtGui.QTextEdit(self.frameLog)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.gridLayout_2.addWidget(self.frameLog, 0, 0, 1, 1)
        self.frameOperation = QtGui.QFrame(self.centralwidget)
        self.frameOperation.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOperation.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOperation.setObjectName(_fromUtf8("frameOperation"))
        self.formLayout = QtGui.QFormLayout(self.frameOperation)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.comboBoxDevice = QtGui.QComboBox(self.frameOperation)
        self.comboBoxDevice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBoxDevice.setObjectName(_fromUtf8("comboBoxDevice"))
        self.comboBoxDevice.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.comboBoxDevice)
        self.frameWaitAdjust = QtGui.QFrame(self.frameOperation)
        self.frameWaitAdjust.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameWaitAdjust.setFrameShadow(QtGui.QFrame.Raised)
        self.frameWaitAdjust.setObjectName(_fromUtf8("frameWaitAdjust"))
        self.gridLayout = QtGui.QGridLayout(self.frameWaitAdjust)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBox_waitAdjust = QtGui.QSpinBox(self.frameWaitAdjust)
        self.spinBox_waitAdjust.setMinimum(-1000)
        self.spinBox_waitAdjust.setMaximum(1000)
        self.spinBox_waitAdjust.setSingleStep(100)
        self.spinBox_waitAdjust.setProperty("value", 0)
        self.spinBox_waitAdjust.setObjectName(_fromUtf8("spinBox_waitAdjust"))
        self.gridLayout.addWidget(self.spinBox_waitAdjust, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.frameWaitAdjust)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_waitRandom = QtGui.QSpinBox(self.frameWaitAdjust)
        self.spinBox_waitRandom.setMaximum(3000)
        self.spinBox_waitRandom.setSingleStep(100)
        self.spinBox_waitRandom.setProperty("value", 0)
        self.spinBox_waitRandom.setObjectName(_fromUtf8("spinBox_waitRandom"))
        self.gridLayout.addWidget(self.spinBox_waitRandom, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frameWaitAdjust)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.frameWaitAdjust)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frameWaitAdjust)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.verticalSlider_waitAdjust = QtGui.QSlider(self.frameWaitAdjust)
        self.verticalSlider_waitAdjust.setMinimum(-1000)
        self.verticalSlider_waitAdjust.setMaximum(1000)
        self.verticalSlider_waitAdjust.setSingleStep(50)
        self.verticalSlider_waitAdjust.setPageStep(100)
        self.verticalSlider_waitAdjust.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_waitAdjust.setObjectName(_fromUtf8("verticalSlider_waitAdjust"))
        self.gridLayout.addWidget(self.verticalSlider_waitAdjust, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frameWaitAdjust)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.verticalSlider_waitRandom = QtGui.QSlider(self.frameWaitAdjust)
        self.verticalSlider_waitRandom.setMaximum(3000)
        self.verticalSlider_waitRandom.setSingleStep(50)
        self.verticalSlider_waitRandom.setPageStep(100)
        self.verticalSlider_waitRandom.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_waitRandom.setObjectName(_fromUtf8("verticalSlider_waitRandom"))
        self.gridLayout.addWidget(self.verticalSlider_waitRandom, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.frameWaitAdjust)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 2, 1, 1)
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.frameWaitAdjust)
        self.frame_Info = QtGui.QFrame(self.frameOperation)
        self.frame_Info.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Info.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Info.setObjectName(_fromUtf8("frame_Info"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_Info)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_getMedal = QtGui.QLabel(self.frame_Info)
        self.label_getMedal.setObjectName(_fromUtf8("label_getMedal"))
        self.gridLayout_3.addWidget(self.label_getMedal, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_Info)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_hourlyWage = QtGui.QLabel(self.frame_Info)
        self.label_hourlyWage.setObjectName(_fromUtf8("label_hourlyWage"))
        self.gridLayout_3.addWidget(self.label_hourlyWage, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_Info)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_Info)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_countGameWin = QtGui.QLabel(self.frame_Info)
        self.label_countGameWin.setObjectName(_fromUtf8("label_countGameWin"))
        self.gridLayout_3.addWidget(self.label_countGameWin, 4, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_Info)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_Info)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_operatingTime = QtGui.QLabel(self.frame_Info)
        self.label_operatingTime.setObjectName(_fromUtf8("label_operatingTime"))
        self.gridLayout_3.addWidget(self.label_operatingTime, 1, 2, 1, 1)
        self.label_countGame = QtGui.QLabel(self.frame_Info)
        self.label_countGame.setObjectName(_fromUtf8("label_countGame"))
        self.gridLayout_3.addWidget(self.label_countGame, 3, 2, 1, 1)
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.frame_Info)
        self.gridLayout_2.addWidget(self.frameOperation, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButtonRun, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.runProgram)
        QtCore.QObject.connect(self.spinBox_waitRandom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitRandom)
        QtCore.QObject.connect(self.commandLinkButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.shortcutGrablu)
        QtCore.QObject.connect(self.spinBox_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitAdjust)
        QtCore.QObject.connect(self.spinBox_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.verticalSlider_waitAdjust.setValue)
        QtCore.QObject.connect(self.spinBox_waitRandom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.verticalSlider_waitRandom.setValue)
        QtCore.QObject.connect(self.verticalSlider_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_waitAdjust.setValue)
        QtCore.QObject.connect(self.verticalSlider_waitRandom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_waitRandom.setValue)
        QtCore.QObject.connect(self.spinBox_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitAdjust)
        QtCore.QObject.connect(self.spinBox_waitRandom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitRandom)
        QtCore.QObject.connect(self.verticalSlider_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitAdjust)
        QtCore.QObject.connect(self.verticalSlider_waitRandom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitRandom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GranBlue Chondro ver.β", None))
        self.lineEdit_GoalMedal.setText(_translate("MainWindow", "77777777", None))
        self.label_12.setText(_translate("MainWindow", "枚", None))
        self.checkBox_GoalMedal.setText(_translate("MainWindow", "目標メダル枚数で停止する", None))
        self.checkBox_Reload.setText(_translate("MainWindow", "リロードにより画像認証を回避する", None))
        self.label_13.setText(_translate("MainWindow", "開始時刻1", None))
        self.label_14.setText(_translate("MainWindow", "終了時刻1", None))
        self.timeEdit_Start1.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.timeEdit_End1.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.timeEdit_Start2.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.timeEdit_End2.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.label_15.setText(_translate("MainWindow", "開始時刻2", None))
        self.label_16.setText(_translate("MainWindow", "終了時刻2", None))
        self.checkBox_Schedule2.setText(_translate("MainWindow", "実行スケジュール2を使用する", None))
        self.checkBox_Schedule1.setText(_translate("MainWindow", "実行スケジュール1を使用する", None))
        self.commandLinkButton.setText(_translate("MainWindow", "グラブルを起動", None))
        self.pushButtonRun.setText(_translate("MainWindow", "実行", None))
        self.comboBoxDevice.setItemText(0, _translate("MainWindow", "<ネットワークデバイスの選択>", None))
        self.label.setText(_translate("MainWindow", "待ち時間ズレ調整", None))
        self.label_2.setText(_translate("MainWindow", "待ち時間ランダム幅", None))
        self.label_3.setText(_translate("MainWindow", "遅", None))
        self.label_5.setText(_translate("MainWindow", "速", None))
        self.label_4.setText(_translate("MainWindow", "遅", None))
        self.label_6.setText(_translate("MainWindow", "速", None))
        self.label_getMedal.setText(_translate("MainWindow", "0 [Medal]", None))
        self.label_10.setText(_translate("MainWindow", "累計獲得メダル：", None))
        self.label_hourlyWage.setText(_translate("MainWindow", "000000.00 [Medal/Hour]", None))
        self.label_11.setText(_translate("MainWindow", "ゲームWin数：", None))
        self.label_9.setText(_translate("MainWindow", "稼働時間：", None))
        self.label_countGameWin.setText(_translate("MainWindow", "0 [ 回 ]", None))
        self.label_8.setText(_translate("MainWindow", "ゲーム数：", None))
        self.label_7.setText(_translate("MainWindow", "時給：", None))
        self.label_operatingTime.setText(_translate("MainWindow", "00:00:00 [HH:MM:SS]", None))
        self.label_countGame.setText(_translate("MainWindow", "0 [ 回 ]", None))

