# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anacondaCasino.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frameLog = QtGui.QFrame(self.centralwidget)
        self.frameLog.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameLog.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLog.setObjectName(_fromUtf8("frameLog"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameLog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textEdit = QtGui.QTextEdit(self.frameLog)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.textEdit.raise_()
        self.horizontalLayout.addWidget(self.frameLog)
        self.frameOperation = QtGui.QFrame(self.centralwidget)
        self.frameOperation.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOperation.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOperation.setObjectName(_fromUtf8("frameOperation"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameOperation)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.frameOperation)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.comboBoxDevice = QtGui.QComboBox(self.frameOperation)
        self.comboBoxDevice.setObjectName(_fromUtf8("comboBoxDevice"))
        self.comboBoxDevice.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxDevice, 0, 0, 1, 3)
        self.spinBox_waitAdjust = QtGui.QSpinBox(self.frameOperation)
        self.spinBox_waitAdjust.setMinimum(-1000)
        self.spinBox_waitAdjust.setMaximum(1000)
        self.spinBox_waitAdjust.setSingleStep(100)
        self.spinBox_waitAdjust.setProperty("value", 0)
        self.spinBox_waitAdjust.setObjectName(_fromUtf8("spinBox_waitAdjust"))
        self.gridLayout_2.addWidget(self.spinBox_waitAdjust, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frameOperation)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 10, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frameOperation)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frameOperation)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.frameOperation)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 11, 0, 1, 1)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.frameOperation)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout_2.addWidget(self.commandLinkButton, 12, 0, 1, 5)
        self.label_7 = QtGui.QLabel(self.frameOperation)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 9, 0, 1, 1)
        self.pushButtonRun = QtGui.QPushButton(self.frameOperation)
        self.pushButtonRun.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonRun.setAutoRepeatDelay(300)
        self.pushButtonRun.setObjectName(_fromUtf8("pushButtonRun"))
        self.gridLayout_2.addWidget(self.pushButtonRun, 13, 0, 1, 2)
        self.verticalSlider_waitAdjust = QtGui.QSlider(self.frameOperation)
        self.verticalSlider_waitAdjust.setMinimum(-1000)
        self.verticalSlider_waitAdjust.setMaximum(1000)
        self.verticalSlider_waitAdjust.setSingleStep(50)
        self.verticalSlider_waitAdjust.setPageStep(100)
        self.verticalSlider_waitAdjust.setProperty("value", 0)
        self.verticalSlider_waitAdjust.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_waitAdjust.setObjectName(_fromUtf8("verticalSlider_waitAdjust"))
        self.gridLayout_2.addWidget(self.verticalSlider_waitAdjust, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.frameOperation)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 8, 0, 1, 4)
        self.spinBox_waitRandom = QtGui.QSpinBox(self.frameOperation)
        self.spinBox_waitRandom.setMaximum(3000)
        self.spinBox_waitRandom.setSingleStep(100)
        self.spinBox_waitRandom.setProperty("value", 0)
        self.spinBox_waitRandom.setObjectName(_fromUtf8("spinBox_waitRandom"))
        self.gridLayout_2.addWidget(self.spinBox_waitRandom, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frameOperation)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 7, 1, 1, 1)
        self.label_operatingTime = QtGui.QLabel(self.frameOperation)
        self.label_operatingTime.setObjectName(_fromUtf8("label_operatingTime"))
        self.gridLayout_2.addWidget(self.label_operatingTime, 10, 1, 1, 1)
        self.verticalSlider_waitRandom = QtGui.QSlider(self.frameOperation)
        self.verticalSlider_waitRandom.setMaximum(3000)
        self.verticalSlider_waitRandom.setSingleStep(50)
        self.verticalSlider_waitRandom.setProperty("value", 0)
        self.verticalSlider_waitRandom.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_waitRandom.setObjectName(_fromUtf8("verticalSlider_waitRandom"))
        self.gridLayout_2.addWidget(self.verticalSlider_waitRandom, 6, 1, 1, 1)
        self.label_getMedal = QtGui.QLabel(self.frameOperation)
        self.label_getMedal.setObjectName(_fromUtf8("label_getMedal"))
        self.gridLayout_2.addWidget(self.label_getMedal, 11, 1, 1, 1)
        self.label_hourlyWage = QtGui.QLabel(self.frameOperation)
        self.label_hourlyWage.setObjectName(_fromUtf8("label_hourlyWage"))
        self.gridLayout_2.addWidget(self.label_hourlyWage, 9, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frameOperation)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.frameOperation)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frameOperation)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButtonRun, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.runProgram)
        QtCore.QObject.connect(self.spinBox_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.verticalSlider_waitAdjust.setValue)
        QtCore.QObject.connect(self.verticalSlider_waitRandom, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox_waitRandom.setValue)
        QtCore.QObject.connect(self.spinBox_waitRandom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.verticalSlider_waitRandom.setValue)
        QtCore.QObject.connect(self.verticalSlider_waitAdjust, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox_waitAdjust.setValue)
        QtCore.QObject.connect(self.spinBox_waitRandom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitRandom)
        QtCore.QObject.connect(self.verticalSlider_waitRandom, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MainWindow.changeWaitRandom)
        QtCore.QObject.connect(self.commandLinkButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.shortcutGrablu)
        QtCore.QObject.connect(self.spinBox_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitAdjust)
        QtCore.QObject.connect(self.verticalSlider_waitAdjust, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.changeWaitAdjust)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AnacondaCasino", None))
        self.label_5.setText(_translate("MainWindow", "遅く", None))
        self.comboBoxDevice.setItemText(0, _translate("MainWindow", "<ネットワークデバイスの選択>", None))
        self.label_9.setText(_translate("MainWindow", "稼働時間：", None))
        self.label_6.setText(_translate("MainWindow", "遅く", None))
        self.label_3.setText(_translate("MainWindow", "速く", None))
        self.label_10.setText(_translate("MainWindow", "累計獲得メダル：", None))
        self.commandLinkButton.setText(_translate("MainWindow", "グラブルを起動", None))
        self.label_7.setText(_translate("MainWindow", "時給：", None))
        self.pushButtonRun.setText(_translate("MainWindow", "実行", None))
        self.label_4.setText(_translate("MainWindow", "速く", None))
        self.label_operatingTime.setText(_translate("MainWindow", "0 [HH:MM:SS]", None))
        self.label_getMedal.setText(_translate("MainWindow", "0 [Medal]", None))
        self.label_hourlyWage.setText(_translate("MainWindow", "0 [Medal/Hour]", None))
        self.label_2.setText(_translate("MainWindow", "待ち時間ランダム幅", None))
        self.label.setText(_translate("MainWindow", "待ち時間ズレ調整", None))

